apiVersion: v1
kind: Service
metadata:
  name: href-departments
  labels:
    app: href-departments
spec:
  type: NodePort
  selector:
    app: href-departments
  ports:
    - name: href-departments
      protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
