apiVersion: v1
kind: Service
metadata:
  name: href-locations
  labels:
    app: href-locations
spec:
  type: NodePort
  selector:
    app: href-locations
  ports:
    - name: href-locations
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001
