apiVersion: v1
kind: Service
metadata:
  name: href-employees
  labels:
    app: href-employees
spec:
  type: NodePort
  selector:
    app: href-employees
  ports:
    - name: href-employees
      protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30003
